### ISSUE TITLE
Only "on" events get "invalid time" error

### ISSUE THREAD

**Issue by moryoav** [mrgadget/node-red-contrib-eztimer#25]
Sometimes I want only "on" event without an "off" event. So I set a time for "on" and for "off" I select "Input Trigger". That does it, the node will only fire when the "on" time arrives. However, the status of the node turns into "Invalid Time:" or "Invalid Time: [time]". 
The correct behavior: if the user selects "Input Trigger" and there's no input available then the status should only be "ON @ [ontime]".

**Comment by mrgadget** [comment]
Hi @moryoav - totally agree, and can replicate, so will fix.

In this instance - do you still want the off event there so you can manually trigger it? Or is this an on-only timer?  If so, just set the timer type to `trigger only` under `general info` and it will achieve the same thing (but not be broken!)

**Comment by moryoav** [comment]
Yes, absolutely, "trigger only" solves those cases completely.
However, there's still a case where I'd like to manually feed the "on" time using a payload of "ontime [time]". So I selected "Time of Day" in the On Event and left the actual time empty. Then I send a msg.payload with the time. However, with the "on" time left blank, I get the "invalid time" error. Is there any proper way to leave the time empty without getting the "invalid time" error?

**Comment by mrgadget** [comment]
Agree - no it would appear not I'm afraid.  I had a quick look (it's 1:30am here) and I can't work a couple of things out - will have a more in-depth look tomorrow.

**Comment by mrgadget** [comment]
What do you think the status should show _after_ the following events?

| Event  | Status |
| ------------- | ------------- |
| initial deployment  | ON @ [ontime]  |
| a scheduled `on` event  | ?  |
| a manual `on` event  | ?  |
| a manual `off` event  | ?  |

**Comment by moryoav** [comment]
I don't think the status has to include information about scheduled vs. manual activation types, the user typically just wants to know when is the next "on" or "off" events. Statuses that are too long can get annoying visually. So I would think that the logic should be:

pseudo code:
status = ""
if [on time predefined or injected] then status = "on @ [ontime]"
if [off time predefined or injected] then status = status + "off @ [offtime]"

**Comment by mrgadget** [comment]
I appreciate your perspective, but I don't want to change the behaviour of the whole node so have gone with:

| Event  | Status |
| ------------- | ------------- |
| initial deployment  | ON @ [ontime]  |
| a scheduled `on` event  | ON auto  |
| a manual `on` event  | ON manual  |
| a manual `off` event  | OFF manual until [ontime]  |

I've committed some code which I've briefly tested - can you give it a shot and see if it performs how you'd expect it to?

**Comment by moryoav** [comment]
I just downloaded the latest develop branch and overwrote the folder where the node is (is this the correct way to update before it's in the formal repository?), I still get the same problem though, specifically with this node:
`[{"id":"59899461.20f8dc","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"b674986a.cbd6c8","type":"eztimer","z":"59899461.20f8dc","name":"","autoname":" + ","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"2","ontimesun":"dawn","ontimetod":"","onpropertytype":"msg","onproperty":"payload","onvaluetype":"bool","onvalue":"true","onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"3","offtimesun":"dusk","offtimetod":"dusk","offduration":"","offpropertytype":"msg","offproperty":"payload","offvaluetype":"bool","offvalue":"false","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":490,"y":140,"wires":[[]]}]`

**Comment by mrgadget** [comment]
When I imported that node it came in with a on-type of `Time of Day` with no value and an off-type of `Duration` with no value - hence I get the same errors.

Give this one a go:
```js
[{"id":"cf6f06a9.8614e8","type":"tab","label":"eztimer test","disabled":false,"info":""},{"id":"20629854.902c88","type":"eztimer","z":"cf6f06a9.8614e8","name":"","autoname":"12:00","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"2","ontimesun":"dawn","ontimetod":"12:00","onpropertytype":"msg","onproperty":"payload","onvaluetype":"bool","onvalue":"true","onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"9","offtimesun":"dusk","offtimetod":"dusk","offduration":"","offpropertytype":"msg","offproperty":"payload","offvaluetype":"bool","offvalue":"false","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":800,"y":90,"wires":[[]]}]
```

**Comment by moryoav** [comment]
Yes, your flow works, but what I was looking for, as mentioned, was a case where the Time of Day field is empty and can be "fed" the information with a msg.payload of, for example:
`"ontime 9:30 duration 00:45:00"`
So in the case the Time of Day field is empty, I get the desired result, but the Invalid Time error is still there...
Thank you for the replies!

**Comment by mrgadget** [comment]
Ahhh my mistake. I focussed on fixing the issues in your first post (which I believe is all sorted). But I missed what you were after in the second one. I’ll have a look tonight, I understand what you’re trying to do now. Time of day timer where the time of day isn’t initially known.

**Comment by moryoav** [comment]
Exactly. What I want to achieve is sort of a "programmable" scheduler, where the times are set only from outside inputs. Thanks!

**Comment by mrgadget** [comment]
Righto - have another look now.  Re-worked (and drastically simplified) the status building.   Have just uploaded b82b8be.

**Comment by moryoav** [comment]
Error message is gone, thank you!

**Comment by mrgadget** [comment]
Great - thanks for that. I’m just going to let this sit for a week and run it here to make sure I haven’t introduced any issues prior to publishing to NPM. Can you let me know if you find anything please. 

Thanks!

**Comment by moryoav** [comment]
With the recent update, the status works fine, but I'm getting an error in the debug panel when I deploy\redeploy:
"TypeError: Cannot read property 'inverse' of null"

Example setup:
`[{"id":"d9613eec.ab78a","type":"eztimer","z":"2a2be86.4eff518","name":"","autoname":" + 00:45:00","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"2","ontimesun":"dawn","ontimetod":"","onpropertytype":"msg","onproperty":"payload","onvaluetype":"bool","onvalue":"true","onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"3","offtimesun":"dusk","offtimetod":"dusk","offduration":"00:45:00","offpropertytype":"msg","offproperty":"payload","offvaluetype":"bool","offvalue":"false","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":470,"y":160,"wires":[[]]}]`

**Comment by mrgadget** [comment]
agree - slight tweak, give the new one a go.

**Comment by moryoav** [comment]
Looks ok now, I will keep testing.

**Comment by mrgadget** [comment]
I'm going to close this as I think it's sorted.  Will release to npm in a week or two.  Feel free to re-open (or log another issue) if you come up with anything else.

**Comment by moryoav** [comment]
I seem to still be getting an "invalid time" in one case, see the third option here (instead of the expected status - "scheduling suspended"):

`[{"id":"f09b1d8c.ad301","type":"tab","label":"Flow 2","disabled":false,"info":""},{"id":"322ec2db.2b5f6e","type":"inject","z":"f09b1d8c.ad301","name":"","topic":"","payload":"info","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":270,"y":220,"wires":[["e8f539de.465198","7dcf78f4.9e7168","215f4971.739066"]]},{"id":"98612e6c.64ba7","type":"debug","z":"f09b1d8c.ad301","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":710,"y":220,"wires":[]},{"id":"e8f539de.465198","type":"eztimer","z":"f09b1d8c.ad301","name":"6:15 Midweek","autoname":"06:15:00 + 01:00:00","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":true,"ontype":"2","ontimesun":"sunset","ontimetod":"06:15:00","onproperty":"payload","onvaluetype":"bool","onvalue":"true","onoffset":"0","onrandomoffset":0,"onsuppressrepeats":false,"offtype":"3","offtimesun":"dusk","offtimetod":"07:15","offduration":"01:00:00","offproperty":"payload","offvaluetype":"bool","offvalue":"false","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":true,"x":480,"y":160,"wires":[["98612e6c.64ba7"]]},{"id":"7dcf78f4.9e7168","type":"eztimer","z":"f09b1d8c.ad301","name":"timer","autoname":" + 00:30:00","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"9","ontimesun":"sunset","ontimetod":"","onproperty":"payload","onvaluetype":"bool","onvalue":"true","onoffset":"0","onrandomoffset":0,"onsuppressrepeats":false,"offtype":"3","offtimesun":"dusk","offtimetod":"","offduration":"00:30:00","offproperty":"payload","offvaluetype":"bool","offvalue":"false","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":false,"sun":true,"x":450,"y":220,"wires":[["98612e6c.64ba7"]]},{"id":"215f4971.739066","type":"eztimer","z":"f09b1d8c.ad301","name":"","autoname":" + 01:00:00","tag":"eztimer","suspended":false,"sendEventsOnSuspend":false,"lat":"32.0853","lon":"34.7818","timerType":"1","startupMessage":false,"ontype":"2","ontimesun":"dawn","ontimetod":"","onproperty":"payload","onvaluetype":"bool","onvalue":"true","onoffset":0,"onrandomoffset":0,"onsuppressrepeats":false,"offtype":"3","offtimesun":"dusk","offtimetod":"dusk","offduration":"01:00:00","offproperty":"payload","offvaluetype":"bool","offvalue":"false","offoffset":0,"offrandomoffset":0,"offsuppressrepeats":false,"mon":true,"tue":true,"wed":true,"thu":true,"fri":true,"sat":true,"sun":true,"x":470,"y":280,"wires":[["98612e6c.64ba7"]]}]`
