### ISSUE TITLE
Node crashing with TypeError 

### ISSUE THREAD

**Issue by mrgadget** [mrgadget/node-red-contrib-eztimer#35]
![image](https://user-images.githubusercontent.com/63652094/90228804-2a173700-de17-11ea-804c-df21fef24969.png)

Hi

Any idea why I get this error ?

Node-RED version 1.1.1

_Originally posted by @Icegames-dk in https://github.com/mrgadget/node-red-contrib-eztimer/issues/6#issuecomment-673952473_

**Comment by mrgadget** [comment]
Actually! I think I do know - I checked and there is some code in there that uses that property - it appears to be calling the function on msg.payload, so I'd suggest that the error you have there is caused by (somehow) sending the node a msg with a null payload. Stab in the dark, but have a look. Still keen on the test flow if you can't work it out.

Upgrade to 1.2.4 that I just published and see if it gives you a nicer error.

**Comment by Icegames-dk** [comment]
I will install Eztimer ver. 1.2.4 when it comes available in Node-Red ver. 1.1.3 with I just updated to. The current version of Eztimer is 1.2.3 with the same problem.

**Comment by mrgadget** [comment]
Ok thanks - it's available on NPM now, so shouldn't be long until Node-Red picks it up.

In the meantime, maybe have a look at your flow and see why you might be sending the node a `null` payload?

1.2.4 will make the error look nicer, but it'll still be an error.

**Comment by Icegames-dk** [comment]
I still can't see the new version in Node Red
![image](https://user-images.githubusercontent.com/63652094/90379359-ede41080-e07a-11ea-9596-a0890f5d5bf3.png)

It's just a simple test timer that gets the same error as the more complex one I use

![image](https://user-images.githubusercontent.com/63652094/90379554-28e64400-e07b-11ea-8ea1-451cb523bc76.png)

**Comment by mrgadget** [comment]
Unfortunately there's not much more I can do.  The [NPM package](https://www.npmjs.com/package/node-red-contrib-eztimer?activeTab=readme) was updated a few days ago and we now just have to wait for node-red to pick that up into their repos.

I'm sure it looks that simple - but the reason you're generating an error is that node on the left that's feeding stuff into your eztimer node - it's doing that with a null payload I suspect.  But with only a screenshot, I can't troubleshoot anything for you.  If you highlight them, and export > to clipboard then paste in here I can get a bit better idea of what's going on.

When 1.2.4 does come down, it's not going to fix your error, just tell you via a node.error message what the problem is rather than throw an exception.

**Comment by Icegames-dk** [comment]
Thanks, I will keep you updated when the new version is released on Node Red.

Here is the TEST code I use

[
    {
        "id": "2304d159.168ede",
        "type": "tab",
        "label": "TEST",
        "disabled": false,
        "info": ""
    },
    {
        "id": "36e4bc6c.916314",
        "type": "debug",
        "z": "2304d159.168ede",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 470,
        "y": 120,
        "wires": []
    },
    {
        "id": "9e318ed1.0c862",
        "type": "status",
        "z": "2304d159.168ede",
        "name": "",
        "scope": null,
        "x": 70,
        "y": 120,
        "wires": [
            [
                "ef6b528f.8cfda"
            ]
        ]
    },
    {
        "id": "ef6b528f.8cfda",
        "type": "eztimer",
        "z": "2304d159.168ede",
        "name": "Timer TEST",
        "debug": false,
        "autoname": "sunset",
        "tag": "eztimer",
        "suspended": false,
        "sendEventsOnSuspend": false,
        "lat": "57.063",
        "lon": "9.9160",
        "timerType": "2",
        "startupMessage": false,
        "ontype": "1",
        "ontimesun": "sunset",
        "ontimetod": "17:00",
        "onpropertytype": "msg",
        "onproperty": "payload",
        "onvaluetype": "num",
        "onvalue": 1,
        "onoffset": 0,
        "onrandomoffset": true,
        "onsuppressrepeats": false,
        "offtype": "1",
        "offtimesun": "dusk",
        "offtimetod": "dusk",
        "offduration": "00:01:00",
        "offpropertytype": "msg",
        "offproperty": "payload",
        "offvaluetype": "num",
        "offvalue": 0,
        "offoffset": 0,
        "offrandomoffset": 0,
        "offsuppressrepeats": false,
        "mon": true,
        "tue": true,
        "wed": true,
        "thu": true,
        "fri": true,
        "sat": true,
        "sun": true,
        "x": 270,
        "y": 120,
        "wires": [
            [
                "36e4bc6c.916314"
            ]
        ]
    }
]

**Comment by mrgadget** [comment]
Excellent - thanks for that.  Easy to spot the issue straight up.  That first node you have is a 'Report' node - the output of the report node is defined it's help pane

![image](https://user-images.githubusercontent.com/700522/90722588-387dbb00-e30f-11ea-89c1-ff2bac74423f.png)

Specifically highlighted - that it produces no (ie `null`) payload.  So that's why eztimer is throwing that error.  What are you trying to achieve by having this node linked to the eztimer node?

**Comment by Icegames-dk** [comment]
Here is the orignal one I use but I can't the timer to activate my light on sunset, ( Sorry for the bad english, I'm Danish :-) 

[
    {
        "id": "a90976b8.78a308",
        "type": "tab",
        "label": "Lys on (Ikea Home Smart )",
        "disabled": false,
        "info": ""
    },
    {
        "id": "c3808c6b.94db1",
        "type": "debug",
        "z": "a90976b8.78a308",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 770,
        "y": 100,
        "wires": []
    },
    {
        "id": "c080125d.03db",
        "type": "eztimer",
        "z": "a90976b8.78a308",
        "name": "Timer",
        "debug": false,
        "autoname": "sunset",
        "tag": "eztimer",
        "suspended": false,
        "sendEventsOnSuspend": false,
        "lat": "57.063160",
        "lon": "9.916160",
        "timerType": "2",
        "startupMessage": false,
        "ontype": "1",
        "ontimesun": "sunset",
        "ontimetod": "17:00",
        "onpropertytype": "msg",
        "onproperty": "payload",
        "onvaluetype": "num",
        "onvalue": 1,
        "onoffset": 0,
        "onrandomoffset": true,
        "onsuppressrepeats": false,
        "offtype": "1",
        "offtimesun": "dusk",
        "offtimetod": "dusk",
        "offduration": "00:01:00",
        "offpropertytype": "msg",
        "offproperty": "payload",
        "offvaluetype": "num",
        "offvalue": 0,
        "offoffset": 0,
        "offrandomoffset": 0,
        "offsuppressrepeats": false,
        "mon": true,
        "tue": true,
        "wed": true,
        "thu": true,
        "fri": true,
        "sat": true,
        "sun": true,
        "x": 110,
        "y": 100,
        "wires": [
            [
                "45510b98.172694",
                "6fee3c36.b2b444"
            ]
        ]
    },
    {
        "id": "6fee3c36.b2b444",
        "type": "api-call-service",
        "z": "a90976b8.78a308",
        "name": "TV Stuen",
        "server": "fe6d4b97.67bc58",
        "version": 1,
        "debugenabled": false,
        "service_domain": "light",
        "service": "turn_on",
        "entityId": "",
        "data": "\"sensor.fjernbetjening_tv_stuen, light.paere_gulv_lampe, light.paere_ph_lampe, light.paere_rund_lampe, light.paere_vaeg\"",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 320,
        "y": 140,
        "wires": [
            [
                "c3808c6b.94db1"
            ]
        ]
    },
    {
        "id": "45510b98.172694",
        "type": "api-call-service",
        "z": "a90976b8.78a308",
        "name": "Spise Stue",
        "server": "fe6d4b97.67bc58",
        "version": 1,
        "debugenabled": false,
        "service_domain": "light",
        "service": "turn_on",
        "entityId": "",
        "data": "\"sensor.fjernbetjening_spise_stuen, light.paere_door_1, light.paere_door_2, light.paere_lille_gulvlampe, light.paere_stor_gulvlampe\"",
        "dataType": "json",
        "mergecontext": "",
        "output_location": "payload",
        "output_location_type": "msg",
        "mustacheAltTags": false,
        "x": 330,
        "y": 60,
        "wires": [
            [
                "c3808c6b.94db1"
            ]
        ]
    },
    {
        "id": "fe6d4b97.67bc58",
        "type": "server",
        "z": "",
        "name": "Home Assistant",
        "legacy": false,
        "addon": false,
        "rejectUnauthorizedCerts": false,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true
    }
]

**Comment by mrgadget** [comment]
No problem - I'm sure my Danish would be worse!

Nothing wrong with your eztimer usage there - it runs fine for me. You could use a debug node on the eztimer output to verify it's firing if you wanted.

The issue you have there is the format you've used in your `data` parameter in your Home Assistant nodes.  You've used
```"sensor.fjernbetjening_tv_stuen, light.paere_gulv_lampe, light.paere_ph_lampe, light.paere_rund_lampe, light.paere_vaeg"```
Where it needs to be valid JSON, and specify them as an array, eg;
```json
{
    "entity_id": [
        "light.paere_gulv_lampe",
        "light.paere_ph_lampe",
        "light.paere_rund_lampe",
        "light.paere_vaeg"
    ]
}
```
That being said - you can't call light turn_on for a sensor element, so drop that too (I've removed it from the sample above).

And again, to 'unit' test this, use an inject node just before the Home Assistant node so it runs immediately - this isolates it so you're not left wondering if it's the timer or the Home Assistant node that's the issue.

Hope that helps, happy home automating!
